---
title: "Overview XYZT variables"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths}

path_cmorized_annual <-
  "/nfs/kryo/work/loher/CESM_output/RECCAP2/submit_Dec2020/split/"

```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
```

# Regions mask

```{r region_masks_all}

region_masks_all <-
  read_csv("data/regions/RECCAP2_region_masks_all_clean.cvs")

```

# File names

```{r read_files_overview}

overview <-
  read_csv("data/overview/overview_files.csv")

# set name of model to be subsetted
experiment_IDs <- c("A", "B", "C", "D")

```

# Plots

Comments:

- 

```{r 3D_variables}

variables <-
  overview %>%
  filter(shape == "XYZT") %>%
  distinct(variable_id) %>%
  pull()

# variables <- variables[1]
# experiment_IDs <- experiment_IDs[1]

for (i_experiment_ID in experiment_IDs) {
  for (i_variable in variables) {
    # i_experiment_ID <- experiment_IDs[1]
    # i_variable <- variables[1]
    
    # read list of all files
    file <- paste(i_variable,
                  "_CESM-ETHZ_",
                  i_experiment_ID,
                  "_1_gr_1980-2018.nc",
                  sep = "")
    print(file)
    
    # read in data
    variable_data <-
      tidync(paste(path_cmorized_annual,
                   file,
                   sep = ""))
    
    # convert to tibble
    variable_data_tibble <- variable_data %>%
      hyper_tibble()
    
    # remove open link to nc file
    rm(variable_data)
    
    variable_data_tibble_climatology <-
      variable_data_tibble %>%
      group_by(depth) %>%
      summarise(
        "mean" := mean(!!sym(i_variable), na.rm = TRUE),
        "min"  := min(!!sym(i_variable), na.rm = TRUE),
        "max"  := max(!!sym(i_variable), na.rm = TRUE)
      ) %>%
      ungroup()
    
    print(
      variable_data_tibble_climatology %>%
        arrange(depth) %>%
        ggplot() +
        geom_ribbon(aes(
          xmin = min, xmax = max, y = depth,
          fill = "min/max"
        ), alpha = 0.3) +
        geom_path(aes(mean, depth, col="mean")) +
        scale_y_reverse()  +
        scale_fill_viridis_d() +
        scale_color_viridis_d() +
        labs(
          title = paste("experiment_ID:", i_experiment_ID),
          y = i_variable
        ) +
        theme(legend.title = element_blank())
    )
    
    
    print(
      variable_data_tibble %>%
        ggplot(aes(!!sym(i_variable), depth)) +
        geom_bin2d(bins = 100) +
        scale_y_reverse()  +
        scale_fill_viridis_c() +
        labs(
          title = paste("experiment_ID:", i_experiment_ID),
          y = i_variable
        )
    )
    
  }
}

```

