---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

On this website we present some initial analysis of the CESM ETHZ model output submitted to RECCAP2-ocean.

This initial analysis covers results from 4 model runs (A-D) with annual (3D variables) or monthly (2D variables) temporal resolution. The diagnosis comprises following aspects:

-   time series of annual mean $\pm$ SD, min, and max values
-   comparison of zonal mean sections against WOA18/GLODAPv2_climatology
-   comparison of surface maps against WOA18/GLODAPv2_climatology

If not stated differently, the above analysis are executed by basin, ie separating the Atlantic, Indian and Pacific Ocean.

Please navigate trough the navbar on top to take a look at the various chapters of this project. The links in the upper right corner bring you to the source code of this project and back to Jens' main homepage.

© Dr. Jens Daniel Müller, ETH Zurich, 2021
