---
title: "Regions"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths}

path_basin_mask <-
  "/nfs/kryo/work/updata/reccapv2/"

```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
```

# Region masks

## region_masks_all

```{r region_masks_all}

region_masks_all <-
  read_ncdf(paste(path_basin_mask, "RECCAP2_region_masks_all.nc", sep = "")) %>%
  as_tibble()

region_masks_all <- region_masks_all %>%
  mutate(seamask = as.factor(seamask))

region_masks_all %>%
  ggplot(aes(lon, lat, fill = seamask)) +
  geom_raster() +
  coord_quickmap(expand = 0)

region_masks_all_seamask <- region_masks_all %>%
  select(lat, lon, seamask)

region_masks_all <- region_masks_all %>%
  select(-seamask)

region_masks_all <- region_masks_all %>%
  pivot_longer(open_ocean:southern,
               names_to = "region",
               values_to = "value") %>%
  mutate(value = as.factor(value))

unique(region_masks_all$value)

region_masks_all %>%
  filter(value != 0) %>%
  ggplot(aes(lon, lat, fill = region)) +
  geom_raster() +
  scale_fill_brewer(palette = "Dark2") +
  coord_quickmap(expand = 0)

region_masks_all %>%
  filter(value != 0) %>%
  ggplot(aes(lon, lat, fill = value)) +
  geom_raster() +
  coord_quickmap(expand = 0) +
  labs(title = "all regions")

region_masks_all %>%
  filter(value != 0) %>%
  group_split(region) %>%
  map(
    ~ ggplot() +
      geom_raster(data = region_masks_all_seamask %>% filter(seamask == 0),
                  aes(lon, lat)) +
      geom_raster(data = .x,
                  aes(lon, lat, fill = value)) +
      coord_quickmap(expand = 0) +
      labs(title = paste("region:", unique(.x$region)))
  )



ggplot() +
  geom_raster(data = region_masks_all %>% filter(value != 0),
              aes(lon, lat, fill = region)) +
  geom_raster(data = region_masks_all_seamask %>% filter(seamask == 1),
              aes(lon, lat)) +
  coord_quickmap(expand = 0)


```

## openocean_1deg

```{r openocean_1deg}


openocean_1deg <-
  read_ncdf(paste(path_basin_mask, "RECCAP2_openocean_1deg.nc", sep = "")) %>%
  as_tibble()

openocean_1deg <- openocean_1deg %>%
  mutate_at(vars("reccap2_ocean_regions":"seamask"), as.factor)

openocean_1deg %>%
  ggplot(aes(lon, lat, fill = reccap2_ocean_regions)) +
  geom_raster() +
  scale_fill_brewer(palette = "Dark2") +
  coord_quickmap(expand = 0)

openocean_1deg <- openocean_1deg %>%
  pivot_longer(atlantic:southern,
               names_to = "region",
               values_to = "value") %>%
  filter(value != 0)

openocean_1deg %>%
  filter(region != "seamask") %>%
  ggplot(aes(lon, lat, fill = value)) +
  geom_raster() +
  scale_fill_brewer(palette = "Dark2") +
  coord_quickmap(expand = 0)

openocean_1deg <- openocean_1deg %>%
  select(-value)

openocean_1deg %>%
  filter(region != "seamask") %>%
  ggplot(aes(lon, lat, fill = region)) +
  geom_raster() +
  scale_fill_brewer(palette = "Dark2") +
  coord_quickmap(expand = 0)

openocean_1deg <- openocean_1deg %>%
  select(lat, lon, region)

```

