---
title: "GLODAP subset variable climate A"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths}

path_cmorized_annual <-
  "/nfs/kryo/work/loher/CESM_output/RECCAP2/submit_Dec2020/split/"

```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
```

# Region masks

```{r region_masks_all}

region_masks_all <-
  read_csv("data/regions/RECCAP2_region_masks_all_clean.cvs")

```

# File names

```{r read_files_overview}

overview <-
  read_csv("data/overview/overview_files.csv")

```

# Time series plots

## iT

Comments:

- fgco2_reg
  - regions not accessible
  - values seem identical to fgco2_glob

```{r regionally_integrated_2D_variables, fig.asp=0.5}

# set name of model to be subsetted
experiment_IDs <- c("A", "B", "C", "D")

# for loop across variables
variables <-
  c(
    "fgco2_glob"
    # "fgco2_reg"
  )

for (i_experiment_ID in experiment_IDs) {
  for (i_variable in variables) {
    
    # i_experiment_ID <- experiment_IDs[1]
    # i_variable <- variables[1]
    
    # read list of all files
    file <- paste(i_variable,
                  "_CESM-ETHZ_",
                  i_experiment_ID,
                  "_1_gr_1980-2018.nc",
                  sep = "")
    print(file)
    
    # read in data
    variable_data <-
      tidync(paste(path_cmorized_annual,
                   file,
                   sep = ""))
    
    # convert to tibble
    variable_data_tibble <- variable_data %>%
      hyper_tibble()
    
    # remove open link to nc file
    rm(variable_data)
    
    print(
    variable_data_tibble %>%
      ggplot(aes(time_mon,
                 !!sym(i_variable))) +
      geom_path() +
      labs(title = paste("experiment_ID:", i_experiment_ID))
    )
    
  }
}

```


## 2D variables (XYT)

Comments:

- 

```{r 2D_variables, fig.asp=0.5}

# for loop across variables
variables <-
  overview %>% 
  filter(shape == "XYT") %>% 
  distinct(variable_id) %>% 
  mutate(variable_id = if_else(variable_id == "pco2atm", "atmpco2", variable_id)) %>% 
  pull()

# variables <- variables[1]
# experiment_IDs <- experiment_IDs[1]

for (i_experiment_ID in experiment_IDs) {
  for (i_variable in variables) {
    
    # i_experiment_ID <- experiment_IDs[1]
    # i_variable <- variables[1]
    
    # read list of all files
    file <- paste(i_variable,
                  "_CESM-ETHZ_",
                  i_experiment_ID,
                  "_1_gr_1980-2018.nc",
                  sep = "")
    print(file)
    
    # read in data
    variable_data <-
      tidync(paste(path_cmorized_annual,
                   file,
                   sep = ""))
    
    # convert to tibble
    variable_data_tibble <- variable_data %>%
      hyper_tibble()
    
        # remove open link to nc file
    rm(variable_data)
    
    variable_data_tibble_climatology <-
      variable_data_tibble %>% 
      group_by(lat, lon) %>% 
      summarise("mean" := mean(!!sym(i_variable), na.rm = TRUE),
                "min"  := min(!!sym(i_variable), na.rm = TRUE),
                "max"  := max(!!sym(i_variable), na.rm = TRUE)) %>%
      ungroup() 
    
    variable_data_tibble_climatology <- variable_data_tibble_climatology %>% 
      pivot_longer(c("mean", "min", "max"),
                   values_to = i_variable,
                   names_to = "parameter")
    
    print(
    variable_data_tibble_climatology %>% 
      ggplot(aes(lon, lat, fill=!!sym(i_variable))) +
      geom_raster() +
      scale_fill_viridis_c() +
      coord_quickmap(expand = 0) +
      facet_wrap(~parameter, ncol = 2) +
      theme(axis.title = element_blank()) +
      labs(title = paste("experiment_ID:", i_experiment_ID))
    )
    
    variable_data_tibble_time_series <-
      variable_data_tibble %>% 
      group_by(time_mon) %>% 
      summarise("mean" := mean(!!sym(i_variable), na.rm = TRUE),
                "min"  := min(!!sym(i_variable), na.rm = TRUE),
                "max"  := max(!!sym(i_variable), na.rm = TRUE)) %>%
      ungroup() 
 
    print(
      variable_data_tibble_time_series %>%
        ggplot() +
        geom_ribbon(aes(
          x = time_mon,
          ymin = min,
          ymax = max,
          fill = "min/max"
        ), alpha = 0.3) +
        geom_path(aes(
          x = time_mon,
          y = mean,
          col  = "mean"
        )) +
        scale_fill_viridis_d() +
        scale_color_viridis_d() +
        labs(title = paste("experiment_ID:", i_experiment_ID),
             y = i_variable
        ) +
        theme(legend.title = element_blank())
    )
    
       
  }
}

```


```{r 2D_variables_wait, eval=FALSE}

# set name of model to be subsetted
experiment_ID <- "A"

# for loop across variables
variables <-
  c("fgco2",
    "spco2",
    "fice",
    "intpp",
    "epc100",
    "epc1000",
    "epc100type / epc1000type",
    "epcalc100",
    "Kw",
    "pco2atm",
    "alpha",
    "tos",
    "sos",
    "dissicos",
    "talkos",
    "no3os",
    "po4os",
    "sios",
    "dfeos",
    "o2os",
    "intphyc",
    "intphynd",
    "intdiac",
    "intzooc",
    "chlos",
    "mld",
    "zeu",
    "dissic",
    "talk",
    "thetao",
    "so",
    "epc",
    "no3",
    "po4",
    "si",
    "o2")

for (i_variable in variables) {
  # i_variable <- variables[1]
  
  # read list of all files
  file <- paste(i_variable,
                "_CESM-ETHZ_",
                experiment_ID,
                "_1_gr_1980-2018.nc",
                sep = "")
  print(file)
  
  # read in data
  variable_data <-
    read_ncdf(paste(path_cmorized_annual,
                    file,
                    sep = ""))
  
  # convert to tibble
  variable_data_tibble <- variable_data %>%
    select(-time_mon) %>% 
    as_tibble()
  
  # remove open link to nc file
  rm(variable_data)
  
  # remove na values
  variable_data_tibble <-
    variable_data_tibble %>%
    filter(!is.na(!!sym(i_variable)))

  variable_data_tibble %>% 
    ggplot(aes(time_mon, as.numeric(fgco2_glob))) +
    geom_path()
  
  # # harmonize longitudes
  # variable_data_tibble <- variable_data_tibble %>%
  #   mutate(lon = if_else(lon < 20, lon + 360, lon))

  # only consider model grids within basinmask
  variable_data_tibble <-
    inner_join(variable_data_tibble, basinmask) %>%
    select(-basin_AIP)
  
  # mutate variables
  variable_data_tibble <- variable_data_tibble %>%
    mutate(month = month(time_mon), !!sym(i_variable) := as.numeric(!!sym(i_variable))) %>%
    select(-time_mon)
  
  # calculate model summary stats
  stats <- variable_data_tibble %>%
    pull(!!sym(i_variable)) %>%
    summary()
  
  stats <- c(year = i_year, variable = i_variable, stats)
  
  if (exists("stats_summary")) {
    stats_summary <- bind_rows(stats_summary, stats)
  }
  
  if (!exists("stats_summary")) {
    stats_summary <- stats
  }
  
  rm(stats)
  
  # subset model at month x lat x lon grid of observations
  model_grid_horizontal <-
    inner_join(Glodap_year_grid_horizontal, variable_data_tibble)
  
  # join model and month x lat x lon x depth grid of observations
  model_obs <-
    full_join(model_grid_horizontal, Glodap_year_grid_depth)
  
  # calculate nr of observations per month x lat x lon grid
  model_obs <- model_obs %>%
    group_by(month, lat, lon) %>%
    mutate(n = sum(!is.na(!!sym(i_variable)))) %>%
    ungroup()
  
  # set variable value from model for observation depth, if only one model depth available
  model_obs_set <- model_obs %>%
    filter(n == 1) %>%
    group_by(lon, lat, month) %>%
    mutate(!!sym(i_variable) := mean(!!sym(i_variable), na.rm = TRUE)) %>%
    ungroup()
  
  # interpolate variable value from model to observation depth
  model_obs_interpo <- model_obs %>%
    filter(n > 1) %>%
    group_by(lon, lat, month) %>%
    arrange(depth) %>%
    mutate(!!sym(i_variable) := approxfun(depth, !!sym(i_variable), rule = 2)(depth)) %>%
    ungroup()
  
  # join interpolated and set model values
  model_obs_interpo <- full_join(model_obs_interpo, model_obs_set)
  rm(model_obs_set)
  
  # subsetted interpolated values at observation depth
  model_obs_interpo <-
    inner_join(Glodap_year_grid_depth, model_obs_interpo) %>%
    select(-n) %>%
    mutate(year = as.numeric(i_year))
  
  # select observation grids without corresponding model subset
  na_model <-
    full_join(Glodap_year_grid_depth, model_obs_interpo) %>%
    filter(is.na(!!sym(i_variable))) %>%
    select(month, lat, lon) %>%
    unique()
  
  # rename interpolated model variable to indicate as model output
  model_obs_interpo <- model_obs_interpo %>%
    rename(!!sym(paste(i_variable, "model", sep = "_")) := !!sym(i_variable))
  
  # add model subset to GLODAP
  GLODAP <-
    natural_join(
      GLODAP,
      model_obs_interpo,
      by = c("year", "month", "lat", "lon", "depth"),
      jointype = "FULL"
    )
  
  # calculate annual average variable
  variable_data_tibble_annual_average <- variable_data_tibble %>%
    fselect(-month) %>%
    fgroup_by(lat, lon, depth) %>% {
      add_vars(fgroup_vars(., "unique"),
               fmean(., keep.group_vars = FALSE))
    }
  
  # select surface annual average variable
  variable_data_tibble_annual_average_surface <-
    variable_data_tibble_annual_average %>%
    filter(depth == min(depth))
  
  # surface map of variable
  map +
    geom_raster(data = variable_data_tibble_annual_average_surface, aes(lon, lat, fill = !!sym(i_variable))) +
    scale_fill_viridis_c(name = i_variable) +
    geom_point(data = model_obs_interpo,
               aes(lon, lat), col = "black") +
    geom_point(data = na_model,
               aes(lon, lat), col = "red") +
    labs(
      title = "GLODAP-based cmorized subset distribution",
      subtitle = paste(
        "Model depth: 5m | Annual average of year",
        i_year,
        "| red = subsetting failed"
      ),
      x = "Longitude",
      y = "Latitude"
    )
  
  ggsave(
    paste(
      path_preprocessing,
      "regular_subset_distribution_runA/",
      i_variable,
      "_",
      i_year,
      ".png",
      sep = ""
    ),
    width = 5,
    height = 3
  )
}

}

# write raw data file for GLODAP-based subsetting model variables
GLODAP %>%
  write_csv(
    paste(
      path_preprocessing,
      "GLODAPv2.2020_preprocessed_model_runA_raw_subset.csv",
      sep = ""
    )
  )

# write file for model summary statistics (original cmorized unit)
stats_summary %>%
  write_csv(
    paste(
      path_preprocessing,
      "regular_subset_distribution_runA/",
      experiment_ID,
      "_summary_stats.csv",
      sep = ""
    )
  )


```
